theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
true-color = true
cursorline = false
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":quit"
w = ":write"
h = ":buffer-previous"
l = ":buffer-next"
x = ":buffer-close"
s = ":vsplit"
S = ":hsplit"

