#!/bin/env sh

while true; do
    DATE=$(date +"󰥔 %H:%M | 󰭨 %a %-d %B")
    BATTERY="󱐋 $(cat /sys/class/power_supply/BAT0/capacity)%"
    xsetroot -name " $BATTERY | $DATE "
    sleep 60
done &

$HOME/dots/bin/setbg -r

picom &
copyq &
dunst &
blueman-applet & 
