#!/bin/env bash

source ~/Dots/bin/alias.sh

export HISTSIZE=1000
export HISTFILESIZE=10000
export HISTFILE=$HOME/.config/bash/history
export INPUTRC=$HOME/.config/bash/inputrc
export HISTCONTROL=erasedups:ignoredups:ignorespace # No duplicate lines or space

shopt -s checkwinsize # Update Window
shopt -s histappend   # Resorect session history
printf %b '\e]4;4;#6495ed\a'

export PS1='\[\e[0;36m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]: \[\e[0;35m\]\w\[\e[0m\]  '
eval "$(zoxide init bash --cmd j)"
# eval "$(starship init bash)"

alias fh="history | fzf --tac --no-sort +s --reverse | sed 's/^[ ]*[0-9]*[ ]*//'"
alias ac="source ./env/bin/activate"
alias de="deactivate"

md(){
	mkdir -p "$1"
	cd "$1"
}

cpg(){
	if [ -d "$2" ];then
		cp "$1" "$2" && cd "$2"
	else
		cp "$1" "$2"
	fi
}

mvg(){
	if [ -d "$2" ];then
		mv "$1" "$2" && cd "$2"
	else
		mv "$1" "$2"
	fi
}

