manager.append_keymap = [
	{ on = [ "g", "h" ], run = 'cd ~', desc = "Go to Home" },
	{ on = [ "g", "a" ], run = 'cd ~/Desktop', desc = "Go to Desktop" },
	{ on = [ "g", "d" ], run = 'cd ~/Downloads', desc = "Go to Downloads" },
	{ on = [ "g", "D" ], run = 'cd ~/Documents', desc = "Go to Documents" },
	{ on = [ "g", "v" ], run = 'cd ~/Videos', desc = "Go to Videos" },
	{ on = [ "g", "p" ], run = 'cd ~/Pictures', desc = "Go to Pictures" },
	{ on = [ "g", "s" ], run = 'cd ~/Pictures/Screenshots', desc = "Go to Screenshots" },
	{ on = [ "g", "n" ], run = 'cd ~/Notes', desc = "Go to Notes" },
	{ on = [ "g", "." ], run = 'cd ~/Dots/.config', desc = "Go to Dots" },
]

[[manager.prepend_keymap]]
on   = [ "q" ]
run  = 'close'

[[manager.prepend_keymap]]
on   = [ "." ]
run  = 'hidden toggle'

[[manager.prepend_keymap]]
on   = [ "n" ]
run  = 'create'

[[manager.prepend_keymap]]
on   = [ "o" ]
run  = 'shell "xdg-open $@" --confirm'

[[manager.prepend_keymap]]
on   = [ "i" ]
run  = 'shell "$SHELL" --block --confirm'

[[manager.prepend_keymap]]
on   = [ "I" ]
run  = 'shell "thunar" --confirm'

[[manager.prepend_keymap]]
on   = [ "e" ]
run  = 'shell "$EDITOR $@" --block --confirm'

[[manager.prepend_keymap]]
on   = [ "E" ]
run  = 'shell "sudo nvim $@" --block --confirm'

[[manager.prepend_keymap]]
on   = [ "'" ]
run  = 'shell "setbg \"$@\"" --block --confirm'
