#!/bin/env sh

$HOME/dots/bin/setbg -r

battery="/sys/class/power_supply/BAT0"
[ ! -d "$battery" ] && battery=""

while true; do
	[ $battery ] && {
		cap=$(cat $battery/capacity)
		[ $cap -lt 15 ] && notify-send "🪫 low battery"
		BATTERY=" 󱐋 $cap% "
	}
	DATE=" $(date +"󰥔 %H:%M  󰭨 %a %-d %b") "
	xsetroot -name "$BATTERY$DATE"
	sleep 60
done &

copyq &
picom --vsync &
dunst -conf ~/.config/dwm/lib/dunstrc &
