#!/bin/env sh

$HOME/dots/bin/setbg -r

while true; do
	DATE=$(date +"󰥔 %H:%M | 󰭨 %a %-d %B")
	BATTERY="󱐋 $(cat /sys/class/power_supply/BAT0/capacity)%"
	xsetroot -name " $BATTERY | $DATE "
	sleep 60
done &

copyq &
picom --config ~/.config/dwm/lib/picom.conf &
dunst -conf ~/.config/dwm/lib/dunstrc &
