#!/bin/env sh

$HOME/dots/bin/setbg -r

battery="/sys/class/power_supply/BAT0"
[ ! -d "$battery" ] && battery=""

while true; do
	[ $battery ] && BATTERY=" 󱐋 $(cat $battery/capacity)% | "
	DATE="$(date +"󰥔 %H:%M | 󰭨 %a %-d %B") "
	xsetroot -name "$BATTERY$DATE"
	sleep 60
done &

copyq &
picom --config ~/.config/dwm/lib/picom.conf &
dunst -conf ~/.config/dwm/lib/dunstrc &
