#!/bin/env bash

format="bestaudio"
options="--cache-secs=20 --speed=1 --video=auto --quiet "

usage() {
	echo "Usage: $0 [-n] [-s] [-l|-m|-h] [URL/Search]"
	echo "  -n: No resume"
	echo "  -w: Forcw window"
	echo "  -s: Shuffle playlist"
	echo "  -l: Low quality video (480p)"
	echo "  -m: Medium quality video (720p)"
	echo "  -f: High quality video (1080p)"
}

while getopts "snwlmfh" opt; do
	case $opt in
		s) options+="--shuffle " ;;
		n) options+="--no-resume-playback  " ;;
		w) options+="--force-window " ;;
		l) format="bestvideo[height<=480]+bestaudio" ;;
		m) format="bestvideo[height<=720]+bestaudio" ;;
		f) format="bestvideo[height<=1080]+bestaudio" ;;
		h) usage && exit 0 ;;
		*) usage  && exit 1 ;;
	esac
done

shift $((OPTIND-1))

# handle: url
[[ $1 == http* ]] && mpv --ytdl-format="$format" $options "$@" 2>/dev/null && exit 0

# handle: search
search=${*:-$(read -p "search: " search && echo "$search")}
[ -z "$search" ] && exit 1

yt_id=$(yt-dlp --get-id "ytsearch:$search" 2>/dev/null)
[ -z "$yt_id" ] && echo "no results found for: $search" && exit 1

mpv "https://youtu.be/$yt_id" --ytdl-format="$format" --watch-later-dir=/dev/null $options 2>/dev/null
