#!/usr/bin/env fish

function check; command -v $argv &>/dev/null; end
function menu; fzf -e --height 100% --preview "$argv"; end

set all 0
set t $argv

switch "$argv[1]"; case "all" "a"
	set all 1
	set t $argv[2..-1]
end

if check "pacman"
	test (count $t) -eq 0 && set t (pacman -Qq | menu 'pacman -Qi {}')
	test -z "$t" && exit

	test $all -eq 1 && sudo pacman -Rns $t
	or sudo pacman -R $t

else if check "apt"
	test (count $t) -eq 0 && set t \
		(apt list --installed | cut -d/ -f1 | menu 'apt-cache show {}')
	test -z "$t" && exit

	test $all -eq 1 && sudo apt autoremove --purge $t
	or sudo apt remove $t

else
	echo "error: unsupported distribution" >&2 && exit 1
end
