#!/bin/env fish

set conf "$HOME/.config/niri/src/rofi.rasi"
function menu; rofi -config $conf -dmenu -p '' $argv 2>/dev/null; end
function run; rofi -config $conf -show run 2>/dev/null; end

switch "$argv"
	case "dmenu" "d" ""
		menu
	case "run" "r"
		run
	case "clip"
		cliphist list | sed -r 's/([0-9]+)\s+(.*)/\1 \2/' \
			| menu | awk '{print $1}' | xargs cliphist decode | wl-copy
	case "emoji"
		command cat ~/dots/misc/{emotes,nf-icons} \
			| menu | awk '{print $1}' | tr -d '\n' | wl-copy
	case "book"
		cd $HOME/notes/$(date +%Y)
		ls | command rg .pdf | menu | xargs -r zathura
	case "*"
		echo "invalid command!" & exit 1
end
