#!/bin/env fish

function menu
	rofi -config "$HOME/.config/niri/src/rofi.rasi" $argv 2>/dev/null
end
function dmenu; menu -dmenu -p '' $argv; end
function run; menu -show run; end

switch "$argv"
	case "" "d" "dmenu"
		dmenu
	case "r" "run"
		run
	case "c" "clip"
		cliphist list | sed -r 's/([0-9]+)\s+(.*)/\1 \2/' \
			| dmenu | awk '{print $1}' | xargs cliphist decode | wl-copy
	case "e" "emoji"
		command cat ~/dots/misc/{emotes,nf-icons} \
			| dmenu | awk '{print $1}' | tr -d '\n' | wl-copy
	case "b" "book"
		cd $HOME/notes/$(date +%Y)
		ls | command rg .pdf | dmenu | xargs -r zathura
	case "*"
		echo "invalid command!" & exit 1
end
