gui:
  expandFocusedSidePanel: true
  showFileTree: false
  showRandomTip: false
  showCommandLog: false
  showPanelJumps: false
  showBottomLine: true
  # border: hidden
  statusPanelView: allBranchesLog
  theme:
    selectedLineBgColor:
      - black
    activeBorderColor:
      - yellow
    inactiveBorderColor:
      - '#ccc'

os:
  editAtLine: 'nvim +{{line}} {{filename}}'
promptToReturnFromSubprocess: false
disableStartupPopups: false
