#!/bin/env sh

while true; do
    DATE=$(date +"󰥔 %H:%M | 󰭨 %a %d %B")
    BATTERY=$(cat /sys/class/power_supply/BAT0/capacity)
    STATUS=" 󱐋 $BATTERY% | $DATE "
    xsetroot -name "$STATUS"
    sleep 60
done &

xrandr --output eDP-1 --primary --output DP-1 --off
$HOME/dots/bin/setbg -r

copyq & 
dunst &
blueman-applet & 
syncthing serve &

$HOME/dots/bin/notes
