#!/bin/env sh

export DISPLAY=:0
export XDG_SESSION_TYPE="x11"

while true; do
    DATE=$(date +"󰥔 %H:%M | 󰭨 %b %d (%a) %Y")
    BATTERY=$(cat /sys/class/power_supply/BAT0/capacity)
    STATUS=" 󱐋 $BATTERY% | $DATE "
    xsetroot -name "$STATUS"
    sleep 60
done &

blueman-applet & copyq & dunst & battery_warning &

xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off
$HOME/dots/bin/setbg -r

syncthing serve &

$HOME/dots/bin/notes
