[cursor]
blink_interval = 400
unfocused_hollow = false

[cursor.style]
blinking = "on"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "MonaspaceRadon"

[font.bold_italic]
family = "MonaspaceRadon SemiBold"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/fish"

[window]
opacity = 0.9
dynamic_title = true
dynamic_padding = true
padding = { x = 4, y = 4 }
decorations = "none"
startup_mode = "Maximized"

[[keyboard.bindings]]
action = "ResetFontSize"
mods = "Control|Shift"
key = "+"

[[keyboard.bindings]]
action = "CreateNewWindow"
mods = "Alt"
key = "Return"

[general]
live_config_reload = true
import = ["/home/user/.config/alacritty/colors.toml"]
