import = ["/home/user/.config/alacritty/colors.toml"]
live_config_reload = true

[cursor]
blink_interval = 400
unfocused_hollow = false

[cursor.style]
blinking = "on"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "MonaspaceRadon"

[font.bold_italic]
family = "MonaspaceRadon SemiBold"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "="
mods = "Alt"

[mouse]
hide_when_typing = true

[shell]
program = "/bin/fish"

[window]
opacity = 0.85
dynamic_title = true
dynamic_padding = true
padding = { x = 4, y = 4 }
decorations = "none"
startup_mode = "Maximized"

