mgr.append_keymap = [
    { on = [ 'g', 'a' ], run = 'cd ~/Desktop', desc = 'Go to Desktop' },
    { on = [ 'g', 'd' ], run = 'cd ~/Downloads', desc = 'Go to Downloads' },
    { on = [ 'g', 'D' ], run = 'cd ~/Documents', desc = 'Go to Documents' },
    { on = [ 'g', 'v' ], run = 'cd ~/Videos', desc = 'Go to Videos' },
    { on = [ 'g', 'p' ], run = 'cd ~/Pictures', desc = 'Go to Pictures' },
    { on = [ 'g', 's' ], run = 'cd ~/Pictures/screenshots', desc = 'Go to Screenshots' },
    { on = [ 'g', 'n' ], run = 'cd ~/notes', desc = 'Go to Notes' },
    { on = [ 'g', '.' ], run = 'cd ~/dots', desc = 'Go to Dots' },
    { on = [ 'g', ',' ], run = 'cd ~/.config', desc = 'Go to ~/.config' },
    { on = [ 'g', 'l' ], run = 'cd ~/.local', desc = 'Go to ~/.local' },

    { on = [ '.' ], run = 'hidden toggle'},
    { on = [ 'i' ], run = 'shell "$SHELL" --block --confirm'},
    { on = [ 'I' ], run = 'shell "nemo" --confirm'},
    { on = [ 'e' ], run = 'shell "$EDITOR $@" --block --confirm'},
    { on = [ 'E' ], run = 'shell "sudoedit $@" --block --confirm'},
]

mgr.prepend_keymap = [
	{ on = '<S-j>', run = 'arrow 5' },
	{ on = '<S-k>', run = 'arrow -5' },
]
