mgr.append_keymap = [
    { on = [ 'g', 'a' ], run = 'cd ~/Desktop', desc = 'Go to Desktop' },
    { on = [ 'g', 'd' ], run = 'cd ~/Downloads', desc = 'Go to Downloads' },
    { on = [ 'g', 'D' ], run = 'cd ~/Documents', desc = 'Go to Documents' },
    { on = [ 'g', 'v' ], run = 'cd ~/Videos', desc = 'Go to Videos' },
    { on = [ 'g', 'p' ], run = 'cd ~/Pictures', desc = 'Go to Pictures' },
    { on = [ 'g', 's' ], run = 'cd ~/Pictures/Screenshots', desc = 'Go to Screenshots' },
    { on = [ 'g', 'n' ], run = 'cd ~/notes', desc = 'Go to Notes' },
    { on = [ 'g', '.' ], run = 'cd ~/dots', desc = 'Go to Dots' },
    { on = [ 'g', ',' ], run = 'cd ~/.config', desc = 'Go to Dots' },

    { on = [ 'q' ], run = 'close'},
    { on = [ '.' ], run = 'hidden toggle'},
    { on = [ '<Tab>' ], run = 'tab_switch --relative 1'},
    { on = [ 'i' ], run = 'shell "$SHELL" --block --confirm'},
    { on = [ 'I' ], run = 'shell "nemo" --confirm'},
    { on = [ 'e' ], run = 'shell "$EDITOR $@" --block --confirm'},
    { on = [ 'E' ], run = 'shell "sudoedit $@" --block --confirm'},
]
