#!/bin/env bash

if command -v "apt" &>/dev/null ; then
	sudo apt install -y curl fish tmux lf fzf fd-find ripgrep \
		htop bat trash-cli wget fastfetch lazygit sqlite3
	ln -sf "$(which batcat)" ~/.local/bin/bat
	ln -sf "$(which fdfind)" ~/.local/bin/fd
elif command -v "pacman" &>/dev/null ; then
	sudo pacman -Syu --noconfirm curl fish tmux lf fzf fd ripgrep \
		htop bat trash-cli wget fastfetch unzip man-db nvim lazygit
else
	echo "idk"
fi
