#!/bin/env fish

function accept
	read -P "$argv (Y/n) " yn && string match -qr '^[Yy]?$' $yn || return 1
end

if command -v $argv &>/dev/null pacman
	$HOME/dots/bin/i brave-bin
else
	curl -fsS "https://dl.brave.com/install.sh" | sh
end

accept "create brave script" && begin
	echo '#!/bin/env sh'
	echo 'brave-browser --force-device-scale-factor=1.2 $@'
end >"$HOME/.local/bin/brave" && chmod +x "$HOME/.local/bin/brave"
