#!/bin/env fish

function confirm; read -P "$argv (y/N) " | string match -qr '^[Yy]$'; end

confirm "remove the minimize & maximize buttons?" && \
	gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:close'

if confirm "set 10 fixed workspaces"
	gsettings set org.gnome.mutter dynamic-workspaces false
	gsettings set org.gnome.desktop.wm.preferences num-workspaces 10
end

if confirm "set system keybindings"
	for i in (seq 1 9)
		gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-$i "['<alt>$i']"
		gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-$i "['<alt><shift>$i']"
	end
	gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 "['<alt>0']"
	gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 "['<alt><shift>0']"

	gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<alt>h']"
	gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<alt>l']"
	gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<alt><shift>h']"
	gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<alt><shift>l']"

	gsettings set org.gnome.desktop.wm.keybindings close "['<alt>q']"
	gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<alt><shift>m']"
	gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<alt>m']"
	gsettings set org.gnome.shell.keybindings toggle-overview "['<alt>o', '<alt>a']"
	gsettings set org.gnome.shell.keybindings show-screenshot-ui "['<alt>s', 'Print']"
end

if confirm "set custom keybindings"
	gkb set "<alt>z" "xdg-screensaver lock"
	gkb set "<alt>t" "xdg-terminal-exec"
	gkb set "<alt>e" "xdg-terminal-exec e $HOME/Projects"
	gkb set "<alt>i" "xdg-terminal-exec htop"
	gkb set "<alt>w" "xdg-open http://"
	gkb set "<shift><alt>w" "helium --incognito"
	gkb set "<alt>f" "xdg-open file://$HOME"
	gkb set "<alt>r" "setbg"
	gkb set "<alt>n" "sh -c 'cd $HOME/notes && kitty -1 nvim index.md'"
end

if confirm "set kitty as the default terminal"
	echo "kitty.desktop" > ~/.config/xdg-terminals.list
end

if confirm "make the animatations faster"
	command mkdir -p ~/.config/environment.d/
	echo "GNOME_SHELL_SLOWDOWN_FACTOR=0.5" > ~/.config/environment.d/90-gnome-speed.conf
end

if confirm "enable custom extenstions"
	command mkdir -p ~/.local/share/gnome-shell/extensions/
	command ln -sf ~/dots/misc/gnome/thin-panel@anurag ~/.local/share/gnome-shell/extensions/
	gnome-extensions enable thin-panel@anurag
	command ln -sf ~/dots/misc/gnome/workspace-indicator@anurag/ ~/.local/share/gnome-shell/extensions/
	gnome-extensions enable workspace-indicator@anurag
end

confirm "get a nerd-font?" && ~/dots/setup/nf
confirm "setup kanata?" && ~/dots/setup/kanata
return 0
