#!/bin/env fish

set bin "$HOME/.local/bin"

test -f $bin/helium-browser-old && command rm -rf $bin/helium-browser-old
test -f $bin/helium-browser && mv $bin/helium-browser $bin/helium-browser-old

set url (curl -s "https://api.github.com/repos/imputnet/helium-linux/releases/latest" \
	| grep -m 1 "browser_download_url.*x86_64.AppImage" | cut -d '"' -f 4)
curl -L "$url" -o "$bin/helium-browser"

command chmod +x $bin/helium-browser

if test ! -f $bin/helium
	echo -e '#!/bin/env sh\nhelium-browser --force-device-scale-factor=1.2 $@' \
		>"$bin/helium" && chmod +x "$bin/helium"
end
