#!/bin/env fish

function confirm
	read -P "$argv (y/N) " yn && string match -qr '^[Yy]$' $yn || return 1
end

sudo pacman -S \
	hyprland waybar swaybg swaylock hyprpicker brightnessctl pamixer blueman cliphist \
	dunst nemo rofi kitty pavucontrol playerctl libnotify noto-fonts-emoji imagemagick

confirm "install nerd-fonts?" && ~/dots/bin/install-nf
confirm "setup tlp?" && sudo pacman -S tlp && sudo tlp start
confirm "ufw?" && ~/dots/bin/setup/ufw

command mkdir -p ~/Pictures/wallpapers
test -z "$(ls ~/Pictures/wallpapers)" && confirm "get a random wallpaper?" \
	&& command wget -O "$HOME/Pictures/wallpapers/$(uuidgen).png" "https://picsum.photos/1920/1080?random"
