#!/bin/env fish
# setup source https://github.com/jtroo/kanata/blob/main/docs/setup-linux.md

function confirm; read -P "$argv (y/N) " | string match -qr '^[Yy]$'; end

# download
if confirm "get kanata bin"
	wget https://github.com/jtroo/kanata/releases/download/v1.10.1/kanata-linux-binaries-v1.10.1-x64.zip
	unzip kanata-linux-binaries-v1.10.1-x64.zip
	sudo mv kanata_linux_x64 /bin/kanata
	command rm -rf kanata*
end

# if the uinput group does not exist, create a new group
sudo groupadd uinput || echo "uinput already exists"

# add your user to the input and the uinput group
sudo usermod -aG input $USER
sudo usermod -aG uinput $USER

# uinput device permissions
echo 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"' \
    | sudo tee /etc/udev/rules.d/99-input.rules
sudo udevadm control --reload-rules && sudo udevadm trigger

# create and enable a systemd daemon service
mkdir -p ~/.config/systemd/user
touch ~/.config/systemd/user/kanata.service
echo """
[Unit]
Description=Kanata keyboard remapper
Documentation=https://github.com/jtroo/kanata

[Service]
Environment=PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin
Type=simple
ExecStart=/bin/sh -c '/bin/kanata --cfg $HOME/.config/kanata/config.kbd'
Restart=no

[Install]
WantedBy=default.target
""" > ~/.config/systemd/user/kanata.service

systemctl --user daemon-reload
systemctl --user enable kanata.service
systemctl --user start kanata.service
# check whether the service is running
# systemctl --user status kanata.service

confirm "reboot now" && systemctl reboot
