#!/bin/env bash
set -eEo pipefail

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin
ln -s ~/.local/kitty.app/bin/kitten ~/.local/bin
