#!/bin/env bash

case "$1" in
	"down")
		find ~ ~/.config -maxdepth 1 -type l -exec unlink {} \;
		unlink ~/.local/bin/jump
		echo "done" && exit
		;;
esac

mkdir -p ~/.config ~/.local/bin ~/Desktop ~/Pictures/{wallpapers,screenshots}

ln -sf ~/dots/config/* ~/.config

for file in ~/dots/config/nonxdg/*; do
	[ -f "$file" ] && ln -sf "$file" "$HOME/.$(basename $file)"
done

ln -sf ~/dots/misc/jump/main ~/.local/bin/jump

echo "done"
