#!/bin/env bash

accept() { read -r -p "$1 [Y/n] " r; [[ $r =~ ^([yY])*$ ]]; }
check() { command -v "$1" &>/dev/null; }

base() {
	if check "apt"; then
		sudo apt install -y curl fish tmux lf fzf fd-find ripgrep \
			htop bat trash-cli wget fastfetch lazygit sqlite3 unzip
		ln -sf "$(which batcat)" ~/.local/bin/bat
		ln -sf "$(which fdfind)" ~/.local/bin/fd
	elif check "pacman"; then
		sudo pacman -Syu --noconfirm curl fish tmux lf fzf fd ripgrep \
			htop bat trash-cli wget fastfetch unzip man-db nvim lazygit
	else
		echo "unsupported distribution"
	fi
}

up() {
	mkdir -p ~/Desktop ~/.config ~/.local/{bin,state} \
		~/Pictures/{wallpapers,screenshots}
	ln -sf ~/dots/config/* ~/.config
	for file in ~/dots/config/nonxdg/*; do
		[ -f "$file" ] && ln -sf "$file" "$HOME/.$(basename $file)"
	done
	ln -sf ~/dots/misc/jump/main ~/.local/bin/jump

	check "fish" || (accept "install base?" && base)
	echo "done"
}

down() {
	find ~ ~/.config -maxdepth 1 -type l -exec unlink {} \;
	unlink ~/.local/bin/jump
	echo "done"
}

case "$1" in
	""|"up") up ;;
	"down") down ;;
	"base") base ;;
	*) exit 1 ;;
esac
