#!/bin/env fish

function die
	echo "error: $argv" >&2 && exit 1
end

set fonts "JetBrainsMono"
test -n "$argv" && set fonts $argv

set repo_url "https://github.com/ryanoasis/nerd-fonts.git"
set font_dir "$HOME/.local/share/fonts"
mkdir -p "$font_dir"

for font in $fonts
	echo -e "\nInstalling '$font'"

	git clone --filter=blob:none --sparse $repo_url || die "cloneing"
	cd nerd-fonts
	git sparse-checkout add "patched-fonts/$font" || die "404"
	find patched-fonts/$font -name "*.ttf" -exec cp {} $font_dir \;

	cd .. && rm -rf nerd-fonts
	echo -e "\n'$font' installed successfully\n\n"
end

fc-cache -f -v
echo -e "\nDone\n\n"
