#!/bin/env fish

function confirm
	read -P "$argv (y/N) " yn && string match -qr '^[Yy]$' $yn || return 1
end

test command -v "pacman" &>/dev/null || exit 1

sudo pacman -S niri waybar swaybg swaylock kitty rofi nemo \
	cliphist dunst libnotify imagemagick brightnessctl \
	pavucontrol playerctl pamixer xwayland-satellite

confirm "get fonts?" && sudo pacman -S \
	ttf-dejavu ttf-liberation ttf-jetbrains-mono-nerd noto-fonts-emoji

confirm "setup ufw?" && ~/dots/setup/ufw
confirm "setup tlp?" && ~/dots/setup/tlp
confirm "setup pipewire?" && ~/dots/setup/pipewire
confirm "setup kanata?" && ~/dots/setup/kanata
confirm "install helium?" && ~/dots/setup/helium

if confirm "get themes?"
	sodo pacman -S nwg-look adw-gtk-theme papirus-icon-theme
	~/dots/bin/i bibata-cursor-theme-bin
end

if confirm "create sessions desktop file"
	sudo mkdir -p /usr/share/wayland-sessions
	sudo sh -c 'echo """
	[Desktop Entry]
	Name=Niri
	Comment=Scrollable-tiling Wayland compositor
	Exec=niri --session
	Type=Application
	DesktopNames=niri
	""" >/usr/share/wayland-sessions/niri.desktop'
end
