#!/bin/env fish

function confirm; read -P "$argv (y/N) " | string match -qr '^[Yy]$'; end

test command -v "pacman" &>/dev/null || exit 1

sudo pacman --needed --noconfirm -S \
	niri waybar swaybg swaylock kitty rofi nemo \
	cliphist dunst libnotify imagemagick brightnessctl \
	pavucontrol playerctl pamixer xwayland-satellite

confirm "get fonts?" && sudo pacman --needed --noconfirm -S \
	ttf-dejavu ttf-liberation ttf-jetbrains-mono-nerd noto-fonts-emoji

if confirm "get themes?"
	sudo pacman --noconfirm -S --needed \
		nwg-look adw-gtk-theme papirus-icon-theme
	~/dots/bin/i bibata-cursor-theme-bin
end

if confirm "create sessions desktop file"
	sudo mkdir -p /usr/share/wayland-sessions
	sudo sh -c 'echo """
	[Desktop Entry]
	Name=Niri
	Comment=Scrollable-tiling Wayland compositor
	Exec=niri --session
	Type=Application
	DesktopNames=niri
	""" >/usr/share/wayland-sessions/niri.desktop'
end
