#!/bin/env fish

function die; echo "error: $argv" >&2 && exit 1; end

switch "$argv"
	case "latest" "l" ""
		set url "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
	case "nightly" "neo" "n"
		set url "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz"
	case "*"
		die "invalid option"
end

command mkdir -p ~/.local/bin ~/.local/share/applications

command curl -LO "$url" || die "during curl"
command tar xzf nvim-linux-x86_64.tar.gz || die "extracting"
command rm -rf nvim-linux-x86_64.tar.gz

test -e ~/.local/nvim-old && command rm -rf ~/.local/nvim-old
test -e ~/.local/nvim && command mv ~/.local/nvim ~/.local/nvim-old
command mv ./nvim-linux-x86_64 ~/.local/nvim
command ln -sf ~/.local/nvim/bin/nvim ~/.local/bin/nvim

if test ! -e ~/.local/share/applications/nvim.desktop
	command ln -sf ~/.local/nvim/share/applications/nvim.desktop ~/.local/share/applications/
end
