#!/bin/env fish

function die; echo "error: $argv" >&2 && exit 1; end
function check; command -v "$argv[1]" &>/dev/null; end

if check "apt"
	sudo apt install -y pipewire pipewire-audio-client-libraries \
		libpipewire-0.3-0 libpipewire-0.3-dev libpipewire-0.3-modules \
		libspa-0.2-bluetooth libspa-0.2-dev libspa-0.2-jack \
		libspa-0.2-modules pipewire-pulse pipewire-alsa
else if  check "pacman"
	sudo pacman --noconfirm -S \
		pipewire pipewire-audio pipewire-pulse pipewire-alsa \
		pipewire-jack pipewire-bluetooth wireplumber
else
	die "unsupported distribution"
end

systemctl --user enable --now pipewire.service
systemctl --user enable --now pipewire-pulse.service
systemctl --user enable --now wireplumber.service
