#!/bin/env fish

function die
	echo "error: $argv" >&2 && exit 1
end

if  command -v $argv &>/dev/null "apt"
	sudo apt install -y tlp
else if  command -v $argv &>/dev/null "pacman"
	sudo pacman -S tlp
else
	die "unsupported distribution"
end

sudo tlp start

echo -e "\nSTART_CHARGE_THRESH_BAT0=70\nSTOP_CHARGE_THRESH_BAT0=91" \
	| sudo tee -a /etc/tlp.conf
sudo systemctl restart tlp
