#!/bin/env fish

function die
	echo "error: $argv" >&2 && exit 1
end

if command -v $argv &>/dev/null "apt"
	sudo apt install -y ufw
else if command -v $argv &>/dev/null "pacman"
	sudo pacman -S ufw
else
	die "unsupported distribution"
end

sudo systemctl enable ufw
sudo systemctl start ufw

sudo ufw default allow outgoing
sudo ufw default deny incoming

sudo ufw enable
sudo ufw status verbose
