#!/bin/env bash

source ~/.config/alias.sh
source ~/dots/bin/helper/jump-init.sh

shopt -s autocd
shopt -s checkwinsize
shopt -s histappend

export HISTSIZE=5000
export HISTCONTROL=erasedups:ignoredups:ignorespace

# prompt
RED='\[\e[31m\]'
GREEN='\[\e[32m\]'
CYAN='\[\e[36m\]'
PINK='\[\e[35m\]'
RESET='\[\e[0m\]'
BASE_PROMPT="${CYAN}\u${RESET}@${GREEN}\h${RESET}:${PINK} \w${RESET} > "
set_prompt() { [ $? -ne 0 ] && PS1="$RED[Error]$RESET\n$BASE_PROMPT" || PS1="$BASE_PROMPT"; }
PROMPT_COMMAND=set_prompt

bind 'set completion-ignore-case on'
bind 'TAB:menu-complete'
bind '"\C-H": backward-kill-word'
bind '"\eq": "exit\n"'

md() { mkdir -p "$1" && cd "$1"; }
cpg() { cp "$@" && cd "${!#}"; }
mvg() { mv "$@" && cd "${!#}"; }
